// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCkbvbtkQFyS6RzbTYbX1TG1SML35ihHo',
    appId: '1:561012561026:web:a3cc2be6906690c8c1109b',
    messagingSenderId: '561012561026',
    projectId: 'fans-arena',
    authDomain: 'fans-arena.firebaseapp.com',
    storageBucket: 'fans-arena.appspot.com',
    measurementId: 'G-0X8QX9T0B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE5ZyB5ej-I1G_lu55IuMkeRphB2DDMTA',
    appId: '1:561012561026:android:e52cda2b353fee24c1109b',
    messagingSenderId: '561012561026',
    projectId: 'fans-arena',
    storageBucket: 'fans-arena.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJI4yDsJS5nlju67p97DPlIoFK3o_BbZ0',
    appId: '1:561012561026:ios:03f6fa1fcac6ac31c1109b',
    messagingSenderId: '561012561026',
    projectId: 'fans-arena',
    storageBucket: 'fans-arena.appspot.com',
    androidClientId: '561012561026-9c9cb7kupegcea2plm4kt15suun5t9q7.apps.googleusercontent.com',
    iosClientId: '561012561026-vbvagfsu2mths4593hd3uqpuf7vf8mpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fansArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJI4yDsJS5nlju67p97DPlIoFK3o_BbZ0',
    appId: '1:561012561026:ios:03f6fa1fcac6ac31c1109b',
    messagingSenderId: '561012561026',
    projectId: 'fans-arena',
    storageBucket: 'fans-arena.appspot.com',
    androidClientId: '561012561026-9c9cb7kupegcea2plm4kt15suun5t9q7.apps.googleusercontent.com',
    iosClientId: '561012561026-vbvagfsu2mths4593hd3uqpuf7vf8mpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fansArena',
  );
}
